name: hear_quran
description: Hear Quran App

version: 1.0.3+6

publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # state management
  flutter_bloc: ^8.1.3

  # routes management
  go_router: ^11.1.2

  # local data management
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # helpers
  get_it: ^7.6.4
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  permission_handler: ^11.0.1
  equatable: ^2.0.5
  logger: ^2.0.2+1
  device_info: ^2.0.3
  url_launcher: ^6.1.14


  # audio service
  just_audio:
    path: ./packages/just_audio
  just_audio_background: ^0.0.1-beta.10
  audio_session: ^0.1.16
  


  # ui packages
  like_button: ^2.0.5
  miniplayer: ^1.0.1
  audio_video_progress_bar: ^2.0.0
  custom_sliding_segmented_control: ^1.7.5
  lottie: ^2.6.0


  # app localization
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  
  # splash screen
  flutter_native_splash: ^2.3.3

  # others


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/quran/surahs.json
    - assets/quran/reciters.json
    - assets/images/reciters/
    - assets/images/icons/
    - assets/audio/empty.mp3
    - assets/animated/
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
    - family: kufi
      fonts:
        - asset: assets/fonts/Droid-Arabic-Kufi.ttf


flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/icons/app_icon.png


